# Generated by Django 5.0.4 on 2024-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('preco', models.CharField(max_length=10)),
                ('quantidade', models.CharField(max_length=100)),
            ],
        ),
    ]
